# Generated by Django 6.0.3 on 2026-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_problemstatement_max_teams_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='room_configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='seating_allocation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
