# Generated by Django 5.0.14 on 2026-04-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_problemstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathoncoordinator',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list, help_text='Assigned responsibilities: problem_statements, teams, analytics'),
        ),
    ]
