# Generated by Django 6.0.3 on 2026-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_team_selected_problem_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
